Feature/display ticket
WildCodeSchool/2109-wns-remote3-taskberry-client pull request #14
Opened 2022-04-01 09:47 UTC by Myriamhi

2022-04-01 12:57 UTC, brdtheo requested changes

2022-04-01 12:57 UTC, brdtheo commented on src/components/TicketColumn.tsx
> +  const { data, loading, error } = useQuery(GET_PROJECT_TICKETS, {
Ajouter le pollInterval pour avoir le refetch des tickets 
```js
const { data, loading, error } = useQuery(GET_PROJECT_TICKETS, {
    variables: { projectId: 1 },
    pollInterval: 500,
  });
```

2022-04-01 12:57 UTC, brdtheo commented on src/components/Cardticket.tsx
> +            console.log("assigneeID", typeof assigneeId);
retirer `console.log` 

```jsx
{members && members.map((item: any) => (
  <MemberAssignee key={item.id} assignee={item.profilePicture} />
))}```

2022-04-01 12:57 UTC, brdtheo commented on src/components/Cardticket.tsx
> +          {members.map((item: any) => {
Ajouter le type `Member` dans `src/models` pour remplacer `item: any` ?

2022-04-01 12:57 UTC, brdtheo commented on src/components/MemberAssignee.tsx
> +import { useQuery } from "@apollo/client";
retirer imports

2022-04-01 12:57 UTC, brdtheo commented on src/components/MemberAssignee.tsx
> +  assignee: any;
assignee est un `string` ?

2022-04-01 12:57 UTC, brdtheo commented on src/components/TicketColumn.tsx
> +    variables: { projectId: 2 },
ajouter le `pollInterval` pour avoir les changements en "temps réel"

```js
  const { data, loading, error } = useQuery(GET_PROJECT_TICKETS, {
    variables: { projectId: 1 },
    pollInterval: 500,
  });
```

2022-04-01 12:57 UTC, brdtheo commented on src/components/TicketColumn.tsx
> +  if (error) return <div>`Error! ${error.message}`</div>;
ajouter les accolades 
```jsx
if (error) return <div>{`Error! ${error.message}`}</div>;
```

2022-04-01 12:57 UTC, brdtheo commented on src/components/TicketColumn.tsx
> +      {tickets.map((item: any) => {
`tickets && tickets.map` pour éviter le warning `undefined` si aucun ticket
+ ajouter type sur `item` si existant

2022-04-01 12:57 UTC, brdtheo commented on .eslintrc.js
> +    "react/jsx-key": "off"
Ajouter en local et mettre le .eslintrc dans le `.gitignore`

2022-04-01 13:51 UTC, Myriamhi commented on src/components/TicketColumn.tsx
> +  const { data, loading, error } = useQuery(GET_PROJECT_TICKETS, {
corrections faites :)

2022-04-28 16:05 UTC, brdtheo approved these changes

2022-05-24 08:28 UTC, merged